language: node_js
git: {depth: 1}
node_js: [6, 7]
cache:
  bundler: true
  directories: [node_modules, $(npm root -g), $(npm config get prefix)/bin]
branches:
  only: [master, dev, stage, test]
before_install: [npm install -g run-jst]
script: jst run unit
env:
  global:
  - {secure: rkSwyNLfGe78bb0q5PyIyxgyc0p723AjsoiAtQ5IHGBcNiayfEOUZlOZUhJ75RG/zK0LafwjAkZGttrNjhOHbNbEW8Sz01+RbvJw1+Gna4DgvbRP4bT/UYtjGUHXSIr3pFqY+WNdexEzcJgf6LWf3ijnynvuXzjV3u5CNwqQygTpo6XnNzLzdEemmtYn1xV4RqDWfENeBNxsnePgPvmWP0xOgmMffPnRZhMyP2PtvW7++BVzZfCDcvEvAmLLTWXWCNh9g8vwWUafmICN3+QzANSdKnu/ZWkVDyhBpelc5RM46CBmklYWvQxW3DD5RRC97Agn/qNDeZNO5FJoXqT1FEOHACXno5QLkBb9j4ssjcMqVu9Bf/I5T3n6JvvTY74ekwhEcSmWPRZIY2JFR4uN507/KZTYxFv39GGgExja2W0iEaMBPgRlAbDc4xoO43FhoH68xxCMyRwMhoZRyRIfATeAgyn/PeUIQE3j9Xg3Y0gEEcfIG9EbnjVixPFCsV9Zo6DRc5nluAiVj2VFU6nr8BkF9poxSc+GQPONpB2bGhuz261Uc/inavaXds+AzWiatibrZKhNq2KPBb8t27E8Kq0Lt+nGE60U+beucRYx6JsuLUh+BNsMhFm/M5Lmhap5S3/xy6OgDELxgVFLIQrWMkKV5EMBaSJ70L9CGtLB5Rs=}
