language: node_js
sudo: false
node_js:
- '0.12'
cache:
  directories:
  - $(npm root -g)
branches:
  only:
  - master
  - stage
  - test
  - dev
env:
  global:
  #JSPM_GITHUB_AUTH_TOKEN=[secured]
   - secure: sWMknQEOsc+sj3mxknLTVAXPbdLXvLgtcoO7ONTsFKqlpR7K9ld5bDRUNJ/+eHSuE1z5goGtH1gOwh7c7PJCvFOkdEpoXaO+iIwrC2XZ3s2wxUlnHLM6E4OymnSQ8zKr3SeJFUvgMsCbvY0PyXfmW6I6KC7xrDQKTonNYYQdL/6ys8wQQ+Poym3Ml34mIIcLECQSE6OgKxOlV5bFMMFvaUJgOvNr/aypxexBYo1A1W7Q+omjtCD+gaiN4IeXF+DBhKPyOCyfyAGqcjSbHTa33CPSBVrMRRpcQDxQqHWPiATzIk5Pz9P+bKPg1FQuTW2CEMxiPlNHTmTtIVqFa4gfpzo4M4Xi2zwDM8STEP/fy6ohPha7Fl429DMUBqLR3/NABqGARJBhYPbTGJ96HF6Rm7cT1VM3o84ajyWHgS0O1hq4g4Ckw7jHUw4lyKwLF3S547wu0893MZTgtaNlH2BobKhc0kJd8Nys2WhquLt/zImtxpZ9gU7ETl1XA/x6gl7ZzZqg7DTSveNzPK5BbTtEiW1u3o+lVjPFBnG+qvU122kVjD0mVlXBiue6MtsM6yjxF63y8I0oWOPQ+ncQvNP0Pc+KJeQbLr1bnAZuJ/CHo+2mqg0gH1B9+oT+abXY4SafAGcjTAuOlADXjVXp+txoMuGlg95FS7WiRN2eBVAMHkk=
  #CODACY_PROJECT_TOKEN=[secured]
  - secure: YCfNF2UrRXmVuJvaswN4Kk3fOkxI7hmo8Q2S5svpkQMiq3sNZzyGZrpmFK3GRZaddB5t0kHNVdAlZF296+O9scogobDgi2V5GSKpO9pXibtgQGlG3FIcJRmpXSThISXLdP8PL6cOTuln2rvV3A/Q+/uRJAu0BKcKr7nxuTHpl9syFogT7fX/c3bSd70yFBNdf/GCgHpBDMKlHdTf0zwUVaGcYdt6DHzqTDbbPOEoGReOPtuPYnO86dIuClt9AzPzatGYerLloiqtwGrdsuD5UpmDn1tNKv/IpzqEbagtWlTxb1Nwa2i4iNZyYZlJX8Ky8wM8e/JAPlC/d6T2i2Nbcdd91c0QY2TiWml7ayroOhhr0m0Wm2ybk/3sKnmzhR9rBXtgq1oEsuDwU9nPA+MltyFhR3b8bbrdidLL/zoES3JIKD5sqt7OaSSA0lilFYI5eHAuxTYK1r45l/8TYE9Sx3j5kaQOop3IImTlAGukY6I++vW1aQ9qaR1pZnNN5G2HxuHifOLySOzgzu1uuQMT58rtf0zCCo1lAQlLsVuwx/TirGa6Cp83fBFDarfrjDDJmssUaO23DWG2c/Fk9vZYZcQaLcL2wrbLjFlfnkw7I5x0ddJOfpgyXC12M1VsZuQQYNHmoqQkb0NjifHeKtAXKb8uY+Nitz2bpz6OF3+S1bo=
  #COVERALLS_SERVICE_NAME=[secured]
  - secure: QmpRisaoB1wPpEPgzbp4ueXP3QIRjPbdPoMbUlEmL8+7w7uzGS0pPxKmkKztUY17cohbv5Bi39P6k2tA5N+7iDxzQDwNhZ/npNvVpcYktEjEudb8TS0aqGMfdVwVs152e91BUJxNQQwvcpScoyWn/RJRhSd48JRDsO+W6XhJE82LJSvpozc4S2kzu57Px1+xFOUBIPDjdNMyIfREjDo7Ok602/vnUgWYOiwcuDPXXiY0PYG2Z5NwLuldFk1FvOXMQO81RYjCxQBX7D+09PRfnE+TkhsKfzCEqhgqXPufJ0cjgUfL8Jnh94om6Q+/CZqgvlXpNz1mcvtyiYejwS68YMg6GxOqyD+yjeb6RyTIlwJ294UdPQ0v+fkk9d4MSSOBvyvKaiPq+v0eAlPqj/2h6g22QNXQCewC0f2ApunVdYnju7m3qHWXa8YrC1a9IuFI9bcusnST0lojk9sS8hUkyjU51Q+u+u7YPCzmCwNq2oAZyuAtU7dz23wOJGEGyZY2PM/JTo9fOL/JiLVsxVhZC2zA5YHrzCcvZ7VW/C9C2HbVKH87Z2KY9x0/CJ/OI+KbBLiZJ8l2cQNZzjZoMC5Nmx/k7IygXXWNrJRkf5bFjzhTCeg4V7zcx4YdFr0592luJtOxVdE6VlDPfBstaMTR40QlEXyGVL2XvwPaQGegito=
  #COVERALLS_REPO_TOKEN=[secured]
  - secure: eqC7tROtM2iEcXb4AhHuZ2YSqVqTPs3hD07Et3IxNeZq0hobqGHBYJGaOcrzLWrh2Oia3BYXq4jU7LbDH9NL+Bz7OFDcIoneZxA7n75zrTDt9Z307ezDl8NbVyqdnj48CsTK2FEMT03lSNKhYB34013MGyKEbGwOoS78ORt77ZgSHnogK3whBT6bc3RS7kzbJ3VlQKdA2/XwOvWZcGq240LD7fPyhJeuR60ig5h9/OU/p3jdXKyZIsDMjNlsIkXvB9Oh2gUnXrFoeQZmXq5X8lgvPBgPZSODKY7du9OMeQugPJtnwo+RC6WZQcuSdPafFy96ZH/sL/5dZS8o4GJAQ8AIW6w35B/WzBQjvtzfqbf4dPZ5VDPfLuXgcflvZ9u8ZCeDPqw/SvVVD1Rup5Q6SWmqyX2m/JnkA0+fUE+mnid/gErLNFkqq25lQ5JC1QvEt81mkHwPjNkCT3pzkzxrp9Zy/HH7KMKWNQXx/5Jjp8naWFbr/ulDw0TdHP71PjGF+iVYkujjZvDISnnLmn1bXRMU9SgdGZl0N1wplbzQ6v0UQFGvA6UErdxRRUwEbUJwiP31KCmt19Ui1huHgIri7W/BRrJO3hMMB01Pn7VsAkMlrk5DKEfXIugRB5Y6GwNr6KYCz/wadcGIpoSZ9GL8GBF0yrCxIZ3SuOZBd0K7aVQ=
before_install:
- npm install -g babel
- npm install -g browserify
- npm install -g mocha
- npm install -g mocha-babel
- npm install -g istanbul
- npm install -g coveralls
- npm install -g codacy-coverage
- npm install -g istanbul-combine
- cp test/package.json .
- test/bin/setup_npm.sh
after_success:
- npm run coverage