language: node_js
sudo: false
node_js:
- '4.3'
- '6.10'
- '7.7'

cache:
  directories:
  - $(npm root -g)
  - node_modules
  - $(npm config get prefix)/bin

branches:
  only:
  - master
  - dev
  - stage
  - test

before_install:
- (npm list -g babel-cli --depth=0 || npm install -g babel-cli@6.x.x)
- (npm list -g babel-polyfill --depth=0 || npm install -g babel-polyfill)
- (if [ ! -d "node_modules/babel-preset-es2015" ]; then npm install babel-preset-es2015; fi)
- (npm list -g deepify@$(npm show deepify version) --depth=0 || npm install -g deepify)
- (npm list -g browserify --depth=0 || npm install -g browserify@11.2.x)
- (npm list -g mocha@2.5.x --depth=0 || npm install -g mocha@2.5.x)
- (npm list -g istanbul@^1.0.0-alpha --depth=0 || npm install -g istanbul@^1.0.0-alpha)
- (npm list -g codeclimate-test-reporter --depth=0 || npm install -g codeclimate-test-reporter)
- (if [ ! -d "node_modules/istanbul-combine" ]; then npm install istanbul-combine@0.3.x; fi)
- (if [ ! -d "node_modules/fs-extra" ]; then npm install fs-extra@0.x.x; fi)
- (if [ ! -d "node_modules/github" ]; then npm install github; fi)
- (if [ ! -d "node_modules/aws-sdk" ]; then npm install aws-sdk; fi)
- (if [ ! -d "node_modules/s3" ]; then npm install s3; fi)
- npm install -g src/deep-kernel
- npm install -g src/deep-core
- npm install -g src/deep-validation
- npm install -g src/deep-di
- npm install -g src/deep-cache
- npm install -g src/deep-security
- npm install -g src/deep-log
- test/bin/prepare_to_test.sh
- cp test/package.json .

after_success:
- npm run coverage

########################################################################
#todo - uncomment out when travis will have shared storage between jobs
#https://github.com/travis-ci/travis-ci/issues/6054
#env:
#  matrix:
#  - TEST_SUITE=deep-asset,deep-cache,deep-search
#  - TEST_SUITE=deep-db,deep-di,deep-notification
#  - TEST_SUITE=deep-fs,deep-kernel,deep-log,deep-core
#  - TEST_SUITE=deep-framework
#  - TEST_SUITE=deep-security,deep-validation,deep-event,deep-resource
########################################################################
env:
  global:
  # JSPM_GITHUB_AUTH_TOKEN=[secured]
  - secure: "dOXusGiSaTXZsouFbZpv9lSWnUb+iYSJdf7bcjqT5ihUMMHv8X2RDpiFxsL4n/ymEmkTGeMZY3bJhNdViD8S3mN8FMzTGexa/GCqVZvIu+iITI9rYq5XTPRUAP2AOxOa0yccPVr3eJLJ1dx6WA4vsmjpwliLIyJMBwmw4c/Z6CRHX7XNNTsJ60uGrs7LvP1K53avzTO0lRdF0eboOeiAPBM/u9KRRulsOs3v6ktZ3qPqNeMswk71bMafnKrzctl0tcFBk+XowlF6cCs3uRZ0Kj46jQnfXpaNravB2T0snpwFTFnqJqf+3Dux9L7vqhox22wc1vWoaSFqiEvtZ3fKrYwrJaf2Xdsprv9m0SNSCYzRBqrHOWzE9ZDnzY+Om9H6pSnQe1VBDRXkVO7Di1nN/ev4IOnhwizB1iN0dZnMMgvakg/icRhRNKvDIIKRHnjV0l4Mfz4dOi9t3NZhLFl+eUIuti6qbKpedLObUutfVaIK28P627UjCuos1TtZRxRsB0MJEFB6yaMruiIlU1LGksCbbGmQjpi5D8yA5EOWtf1Jtesh8AYn6PNJ6amcCC8KlBo4dKaDAIbjOcYgikoE4cFbcxFj0EZpfMLADcntaOzhvzDwkrNURAEZxja7iNtitLXYIqaKrto4EYAllGH2AhK8kPKnAGyhkgNTStj9Y94="
  # GITHUB_OAUTH_TOKEN=[secured]
  - secure: "bjwCfJAhfHFy5iEobEj7RxxKsVhSeKUQzikvttuT7Zg1PWFO62k4pWBHjA5aure96Pa2tI2p8s+e4LYguIiTAMDBbIdOEVT9Aw+0dVEX7LAt/n8irsrxcgWK76e282OrjW58JILWXPKedKpw1FIcLQm3E0IIORbvJbsPqn1yx2dAeiErjGidmdgwvadnYn8tmFmg6p0g8SkQaA2R+s70VyXuNgLqsxs8Pufe1aczByhsop7I3NLwP2eorx38Y56vTIZ4Mvcs+wyUjSMOx1CsQVvKxUZ2tmcrJ/Tn/kRIn8nLPvHT0fGNMfchYEEUlq/YL4pZSEagQhmmjuyAoEK2I6xsh/fucG3YCYugmhsGC0yf54gUqq6nzTMvekIC9iZKxQXI9uQu+LVvtcBnXhKYYKCtR/nYCOYlp6iSkekrm45RZSp3x3MP++6yXrVifnE1VXro4C9ajZqnQqiWuH0Tp1wJvOJE2uamZRyypjA7tLkG+ahaZtGrbB5UUykiQBFd7ozlCRfg7bfl2HVqh668lBYJd2NobnwF8kYph+VOWtLiTJrN2kukTRkFH6EUPQ4d3DGTT96JIJ3BEbYwRnngJ7Ra95S8IWwT4ZAED0Htl8iiVbLet4/lGEytJEuhUeLAzJZUmCYu9S42Fq70JZ27PTE7YUubdF3MLMNi1/o4JvE="
  # AWS_ACCESS_KEY_ID=[secured]
  - secure: "RzIpbVs8rTPBigvFC0nesRPVPkVBdQLs8vHjQ8dRDBpOVjxr8CrTeY3wazJspCwKPvS78PV33rYQ+JdL3qf/wFz3BvmznA5GHNHUSG4Ys7x13asj5UpPqiXlFLS3Z3078eyuu5WuVBHU8glpZ0PvLckJXdZvct6KB9fx/j3YakCmLqC9OXQc6WSwV/nV+U+lIvD0bQvxU5VKTIhbGVbZ+aK3agvehYb9HZ9TxdtegKETkK578lxjBqlKQA7mPwAq6BCW1KtTilBFGOXKnQ0XguYnQvUp4aA/sXhflyOA+HOVjtAnu/TP17liCF0t8UIc47esETk0/MLqU2yTQWy4rvs93Kwk/efQoCgvxb8Tucf6+t68JXRgUWvD4npVbRr/Yqr48NxhN23nxObO9k45MATW5VfuBJy8y2ESt6l1ycyhIC1Ge9N1QYP5cupx2Y5VI0rzRBUvE7Otwd1Usm2DTlVvloC9pAuQYE7OvFLz4CHTDXd+rn+NJWWdslsol85fbb3N4A3P0km9DSSuqNbSlR3JmNKmusu0FlaD+yaGPdRjrRXqyyhdHt84qYUJnSobPC6a4glFM/rpcaFXDQyaXlVDYYp6jLB1WjiUyUP3lUH/AZ2kcFIlq7EfXroBEDt98ce2CpEg6uo2uxSfksKHtF58+dbLKQoPqtnHEbSoNw8="
  # AWS_SECRET_ACCESS_KEY=[secured]
  - secure: "t8y9v1tqGQZq22e6Xqxpbu3IDJDIsDwuK3TiahyemAbpXZbcjz+CZjmgqA5TLpG0oV1SUcHAzL+6axAHSzG0HoUyMItMoEd+3liXNJYTI4qGXzsfzbT5BR6h2cw2zmxyELi12jc2xQPpbAhPinoyXvKG/cUKRBM4a82YChUvPMGmgjWilm/333/6CwB7sXwGrMDO8CaJX/tbO6Lyl9r64z2wDzuVsHrzqlmKpVhE7HElurudXg3R7IZLHv7rIZ2cgohbszsH50/ZbMuAnNzHFaYTZYc5f6UD0MMk5ZJBNiwxyGuBwbMHu00Gf9f4zJpxG7s9mnxweOJhrWucO2iy+7u/jjh20aWhr5+xSX5atk+7BzPmJCKmm2hHFPh4QukNNjPMi2GGRRTpywSYb0AmNr/fxDwJX7JyqKoACgiiI7nBi6Jg8d/3/j9JKdmEDVw+5JbLliZuFILMpURdUlWNemAor4ZFkUqqhIW6gmrY3+FOQnZYyTNgjE7dvKyYAIuB0qk1hbkknfQJ4mnXWiq//ya66lmgd0xw20U1/mv75++R0kXocjCOBc1JjVEgFom6lHxEcBeGX96rrJpMwexJ2nLc8/YvYShQa9+JPAEgoWH0QnwVlddzAOgaAWwCLCyX+oTqFBDucCvXBsaDlENFbKpWXy8Dif/eURkFatuzr9I="
  # AWS_DEFAULT_REGION=[secured]
  - secure: "uZDcjc1uO8Sz791hDr7Gjqc0bpB/Y//+B0LuKfENWKot93Ta9f4ezXaq/n+xqJSprqWKSKpsKbPvM1rIu7PIhKzhsix0/4/8cUIx7KKCQEheDfrMRy2gSyrkNpYezAtrG4IDAWOehmkIU194SbB8er7MnPQPOvZ/wmw6ps86scvinpQLIllOJxdYUKIObmOLDNQ+eUC8K5tZ+GjAlhuK8rdDd+x2Hzrm55tvIhRQi5Aa3rXc0rX6S474lo7/WbQQPeJjqUnM1k7hR5fBOFybXEKaqTkNlrSu9kSP8GSWOMDX0qzewhtH4Utxz2nzyBZHAgMVOUlOhHnqjANnInfjF/PoC/FLP9Nyez7mv5i7QiiaKE9ws6HWQIsrqgvZVkwHQHvWxtElmzuscKnQ9OKJKiGz8thZv/1GK80sadZdBtrbHpeDGqMATnxadVkb8lmMq5os1vIYApR5B6rcKE/5MKneacdMqyX8SK0bUDRqnYHmGe7XuRdanOzuZpjxpb1X4FWWP4VCs1OLWeKkE3XAMxgaL8miPryc/GuBqKXdBxUGw08fUbdKwuVIcvRqGTZ+pPNZWEbu4cKgppfxYxYs0S6bp8Ka0AoXrZd9ohvZk/HnbFdl6iSXIpZRaWBkx0C6cUa3UkLv2id9xnO2k9MX6MUzlK3gKDf18OjzjsArspE="
  # AWS_S3_BUCKET=[secured]
  - secure: "j68Kzm/+no2jynwQDWhE4HvlAuIOoJE7SSQrzGG5n1r1kydhRDToixugrUSs2bUCqKWGQCeCr9P8bE3vt6ve5F03HaFx8ghsedArqHS6LiLnH/Hy/ipBGjIn16/llQO6LNOv2kijuf7FxnsKZn2RMuFok9dqyaZUk0ZiRyTHb4jU8NIOjamfGSh9Q9xCx/qaUoi6hip/TIF8RlmzrbnUtjHAenjK1WnI8KSFOgMjcm/OrFkHStW06iDwB05o0GAKQALW81iMzj/b7/3tTk4SYxXLPPY1vinkuu4+oWOzm8HeAW9i6zcCAYCyhRzWiP/5pmoxjYs2wGRI7SWTvDHXORsXShc4rjxFI5Qpi2EoYXKwGTrEt6COdmJalO3e7hgp7k3VIwJLmY/aZNlDPQZny6U32i54nFOigbeo7W9WWZ3lEz2VR773PNdJAtNNy/KVE4ey8MlAMLyIZzJr9KKTEoh1nmTvVRjAw1qnbBGTu5/LZrO+B7oYUKysWLOgFOpCTNQkXMpp57LUwyKfJ8qf6RXmZKHlxEHsqFWxwVnnJ7BJLSxzX5W99gC3WT1pO4bwjhVP1/Nfq+DbrppO0y50zKIziMrGTXzzdtWw1Z5OWaMU9Xv0czFRO7UihtyHKkeULdijaNHR2RWVjY2f7RobPf7jPTTCepgvkFQtPfBMtrY="
  # CODECLIMATE_REPO_TOKEN_DEV=[secured]
  - secure: "d1o58eFI5wCiCOhs+mqSZ7oBch/2GRhZOUSdnKZtMWmXOAX+XPqr8HyUL1O5x1jfST8JTdRyE6b7hIdPJJC12Wds/FZULcHkrmqouJeDMM40P4SmgcoQhYW0NPfnutlIY6r77+/FIqOwo0WESBn/d6dKiDHd/3p9yb/sFQN0uhMBXRK6ld4o+8ziEd1h0vsjjb2W8/mmn+y1baS7/1sJeNvad5QBHLV6ki0MhrocI51iFe/P0nAJWE47lCuOS/yeP94pQ3zdfwK+JJ9kBoTW37Ou01XlYuyhSqsLvEOBstz8mg99yPr10LDZ3UHaA9TligoAVSV712MORIK7vtKRvG+It2T030VgFLGKJQKNiOMa1j6YGitCzCuTYD31wTvKbw65CPaDv285YaM1+sDZfGEp6uSkh8GC3s4fQyJ0Mp/QRxw/BbDflAmqemBuyf5YJ1e3V379FLhrqaLnGsoe0hHTfFrCmMV+opcr90BPBhqZkqO9joGpZhEM3VocNEVxrLzgLUJoka9lBBACv1wV7x5jHuj+lkSsbCFckrhibZv+LQOE+SOhsiloVqRVAovxpiRlJIWYPn5ho9nEOPxDXHOl/I24CD27RSjFAEuYRVNA0N1d6rj0FrRrna02lqfvPt2I7sWYsOzoqsDsUrkYzVs97YSMcS4gRilh1JXqDjA="
  # CODECLIMATE_REPO_TOKEN_MASTER=[secured]
  - secure: "l2NbwnzWbsNv6ndcjBNnpdvbZjA/tOAYzeAYxR8wmQFT9xH5nbYV35e64rwO5HD3TwXlu7a1/cbr+m8nmwL58terVOJXYkx8sEP+9/PEJwFx5+7Wmlfcl+O0HH1EUZBnseLHZl/4xvxvVUZhion29bkMKa42O0S6sf3RiuDS+PbtAYgob6OIFRLPtDKrTk3dzOQX0NdZ1WsN44e/w3ghesXf17NialtMXbgn1iBLOpQ0e+k66DarSILqiGl8uB9iVvgZ101b8wZGJeKN5ACesuADCjJ9tzUM3PQG9SbkunwLQj0sqasYyIV0lZagQIW6fnrw+sP94J4Edpa7vEf9yT+JApRlwBggR8yjxFWliaYfZk32wkj3OdaY+cWEynoTSuWczwPIk6NxjtsCYMt9IMRWafs//TKm0aTF49VqQgDig81xNmlVS6Yg8xzZev+zl5IPAoAh5lmvYM8InfkiwGYxPM6UyYrcqI6+oVNMswnPMElZd7UxClFK/9Iz4PSBkuc7WeJY8DSe6qLx/08UKEhqu3+xGhLXjBtbvIuwXEvPc/E+fuR6Gm+7l575H5QptZUXIExE9AsVtmJxSogP3QE0ChUuwGUOLvpTr3lrWwA1V5b/iLI9aYwnGkRPNFZhjXp2pn8EIevHCl3R92tuQT5+VnG//cyzP3lw64yO0o8="
notifications:
  slack:
    secure: "p5qRyHtn17dfyfue7ZKu1GCr2a+H3Kl8CzxAuSKOQl2eC9ojUfpEwnx12fSJevUM1Hb4bkiu3jyl+UDSKvCchtk/cDvKk/2FERH0Go9J+euLf+3I5HZkVGUI1tks7mGK07lyQmsNrMzWpHt006VkMWNLOdoVzECAIuFuxvufRbWKdXYr2LPPwYkrLxcTTSQ9kwv7EpFySH03zOv+xRPswuAQ0yez6tt1NSu7QwdHW8NCPOm4PK/dnvUT/RPMwpP8IMXG55RDkFW/kOqhh0NjJCtEYNW45vZw24fV8sZKl3BhDAQbKFA2l4ehKaz1mpw97hYIfSFxXPJWxsdkl8sUg4Sfw6BQwazK1+Vd55F6mjLzqQQgVJRpc2h2GVvpr26Mq7k3Myr8BEaYyYsFo/iPVGLPBSQDthG1qOwzG86QSb5zaLdkleLS6OY489x+Zd39tBYmMOvFIBQDf0fe5WJUM8zcnWRue6gNc/8gaiFGXwWAUcwXQlW0DHwONy0y/GfnsKA0PXjHANkzi5jhlhmxWVfy9xiL6zxG6n8kWUxgakPBVieu9VKw9nd9sgmjJAySeTH8D4+6WpPnaTojryZ8cBx6ZUsVVL5cLroQ8ZopIu2tM4rp45GLDDVnr1DuyVW9KOY/tGXEhmXu4HAJs4zoaTHuj4VZe9o7+iFPfzXCPg4="
