language: node_js
git: {depth: 1}
node_js: [6, 7]
cache:
  bundler: true
  directories: [node_modules, $(npm root -g), $(npm config get prefix)/bin]
branches:
  only: [master, dev, stage, test]
before_install: [npm install -g run-jst]
script: jst run unit
env:
  global:
  - {secure: YieF6rYE9E+SEjNXPzTtnj+FM+wd//6xfU5lKLgPEVkAp6e6LYoTi5vMcOdV+NTEzLW7DDMOhEWLnKGdG/WKSQrIrQa+f88Pc70NhWA4VEEqIn3MROobvRXhbdKC952mmpmjgL4HiGYVMdPEDttZEdFMAVdSdqrCReGEUm2cl3iIh0ZE9NPQPGOUFP8XGJrjqFDmp8+rdvqKsAHO7cNOGI9Xx6+fy9tJeltXetuPbQ5RwbMIWIU/niSZWfhNSCkiGiA9iPXes5bYixtQ1jnr0QncfOV3K8WiJksnap6NsmCYICg2RR1mfde0soM+WwZfgezPiOvUfqM+ZwtlEEDIMJ5XJzupuwe8ACusnQ8bXYLEWEi35Hmc5NBs5ufIJvxAa1+1UIeQ72jAqnApAcuIrj7PkcEXLTR6RoNnG8h+VpL3Zi9jZxr0+5DJp6kJiZuVMQdVLrh+K8RzLYdpEQA9FBhOmCC419iB9eo7lVP99J+AB1eFDFhcrOAdypK6f+rmZps9SxfY9K/bEplfkDqm2oO03iDANJi8BcE+yDewbdpI7mggGeAf4zBV7AdRarlcIAaODvAen5HMGCsBgyG/CW3Cg41FyrkquQidfbbZoKbaJYWaPpL/f1sKRZa3u+JW9EubMbZMBKLBkpl2k7vu3DS1I3RirGerb/GnTcOyon4=}